### ISSUE TITLE
Fix code scanning alert - Missing rate limiting [WAITING FOR APPROVAL]

### ISSUE THREAD

**Issue by upayanmazumder** [kspcommunity/kspcommunity.com#32]
Tracking issue for:
- [ ] https://github.com/kspcommunity/kspcommunity.com/security/code-scanning/14

**Comment by dave9123** [comment]
Hi

**Comment by Larssies** [comment]
> Tracking issue for:
> 
> * [ ]  [Missing rate limiting](/kspcommunity/kspcommunity.com/security/code-scanning/14)

Why should we rate limit our own api?
