### ISSUE TITLE
Fix code scanning alert - Missing rate limiting

### ISSUE THREAD

**Issue by upayanmazumder** [kspcommunity/kspcommunity.com#39]
Tracking issue for:
- [ ] https://github.com/kspcommunity/kspcommunity.com/security/code-scanning/13

**Comment by Larssies** [comment]
Why is this feature even a thing?

**Comment by g9aerospace** [comment]
> Why is this feature even a thing?

LoL 🤣

**Comment by g9aerospace** [comment]
Please fix it guys.. I'll be back online again after 3rd June ig ugh

**Comment by Larssies** [comment]
> Please fix it guys.. I'll be back online again after 3rd June ig ugh

Its the same issue as before but with a different api url and it doesnt even do anything cus the JSON file is just filled with fake names.

**Comment by g9aerospace** [comment]
Oh he must have not reviewed the code properly. I'll close this then

**Comment by g9aerospace** [comment]
Should I close it?

**Comment by g9aerospace** [comment]
Alr closing it

**Comment by Larssies** [comment]
> Should I close it?

nah leave it, ill create a new pull request that does the following:

- Delete feedback.js 
- Delete users.js
- everyone happy!

**Comment by g9aerospace** [comment]
Alr alr
